[package]
name = "common-scraper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
scraper = "0.12.0"
url = "2.2.2"
reqwest = { version = "0.11.5", features = ["blocking"]}
